config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
    resources :cabans do
      resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :update] do
    member do
      get :accept, to: "bookings#accept"
      get :refuse, to: "bookings#refuse"
      delete :destroy, to: "bookings#destroy", as: :destroy
    end
  end

  get "dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end
  

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :caban

  validates :status, inclusion: { in: %w(pending accepted declined) }
  validates :end_date, comparison: {greater_than: :start_date}


  include PgSearch::Model
  pg_search_scope :search_by_status,
    against: [ :status ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/caban.rb
class Caban < ApplicationRecord
  include CabanConcern
  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :name, :description, :address ],
  using: {
    tsearch: { prefix: true }
  }

  belongs_to :user
  has_many :bookings
  has_many_attached :photos, dependent: :purge
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_status,
    associated_against: {bookings: [ :status ]},
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/concerns/caban_concern.rb
module CabanConcern
  def booked_dates
    # renvoie un array d'array des dates de debut et de fin de tous les bookings du pokemon
    bookings.where(status: ["accepted", "pending"]).pluck(:start_date, :end_date)
  end

  def simple_format_booked_dates
    # renvoie un array d'array des dates de debut et de fin
    # de tous les bookings du pokemon mais sous la forme stringifiée : "1991-12-28"
    booked_dates.deep_map(&:to_s)
  end

  def booked_dates_json_objects
    simple_format_booked_dates.map do |dates_arr|
      {
        from: dates_arr.first,
        to: dates_arr.last
      }
    end
  end

  def flatpickr_booked_dates_object
    {
      dateFormat: "Y-m-d",
      disable: booked_dates_json_objects
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
  has_many :cabans
  has_many :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    authorize @booking
    @caban = Caban.find(params[:caban_id])
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @caban = Caban.find(params[:caban_id])
    @booking.caban = @caban
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def accept
    @booking = Booking.find_by_id(params[:id])
    @booking.update(status: "accepted")
    authorize @booking
    redirect_to dashboard_path
  end

  def refuse
    @booking = Booking.find_by_id(params[:id])
    @booking.update(status: "declined")
    authorize @booking
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find_by_id(params[:id])
    if @booking.status == "pending"
      @booking.destroy
      authorize @booking
      redirect_to dashboard_path
    else
      redirect_to dashboard_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/cabans_controller.rb
class CabansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @cabans = policy_scope(Caban)
    if params[:query].present?
      @cabans = Caban.global_search(params[:query])
    end


    if params[:order] == "ASC"
      @cabans = @cabans.order(:price)
    elsif params[:order] == "DESC"
      @cabans = @cabans.order(price: :desc)
    end
    
    @markers = @cabans.geocoded.map do |caban|
      {
        lat: caban.latitude,
        lng: caban.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { caban: caban })

      }
    end

  end

  def show
    @caban = Caban.find(params[:id])
    @marker = [{ lat: @caban.latitude, lng: @caban.longitude }]
    authorize @caban
  end

  def new
    @caban = Caban.new
    authorize @caban
  end

  def create
    @caban = Caban.new(caban_params)
    @caban.user = current_user
    authorize @caban
    if @caban.save
      redirect_to caban_path(@caban)
    else
      render :new
    end
  end

  def destroy
      @caban = Caban.find(params[:id])
      @caban.destroy
      authorize @caban
      redirect_to dashboard_path, status: :see_other
  end

  def edit
    @caban = Caban.find(params[:id])
    authorize @caban
  end

  def update
    @caban = Caban.find(params[:id])
    if params["caban"]["photos"] == [""]
      @caban.update(caban_params.except(:photos))
    else
      @caban.update(caban_params)
    end
    authorize @caban
    redirect_to caban_path(@caban), status: :see_other
  end

  private

  def caban_params
    params.require(:caban).permit(:name, :description, :price, :address, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:home]
  def home
  end

  def dashboard
    @cabans_as_p = Caban.where(user: current_user)
    @bookings_as_p = Booking.where(caban: @cabans_as_p)
    @bookings_as_r = Booking.where(user: current_user)
    if params[:status]
      @bookings_as_p = @bookings_as_p.search_by_status(params[:status])
    else
      @bookings_as_p
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cabans/_info_window.html.erb
<%= link_to caban_path(caban), class:"text-decoration-none", style:"color: black; height: fit-content" do %>
          <div class="card-trip">


            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner" >
                <% caban.photos.each_with_index do |photo, index|%>

                  <% if index == 0 %>
                    <div class="carousel-item active">
                      <%= cl_image_tag photo.key, style:"width: 100%; height: 100px;", crop: :fill%>
                    </div>
                  <% else %>
                    <div class="carousel-item">
                      <%= cl_image_tag photo.key, style:"width: 100%; height: 100px;", crop: :fill%>
                    </div>
                  <% end %>

                <% end %>

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>

              </div>
            </div>

            <div class="card-trip-infos">
              <div>
                <h2><%=caban.name.capitalize %></h2>
                <p><%= caban.address.capitalize %></p>
              </div>
              <h2 class="card-trip-pricing"><%= caban.price %>€</h2>
            </div>

          </div>
        <% end %>

app/views/cabans/index.html.erb
<div class="pages px-4">
  <div class="d-flex justify-content-center p-3 search w-100">
    <%= form_with url: cabans_path, method: :get, class: "d-flex w-50" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a caban" %>
      <%= submit_tag "Search", class: "btn btn-primary me-3" %>
    <% end %>
    <div class="dropdown">
      <a class="align-items-center btn btn-secondary d-flex dropdown-toggle h-100" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
        Trier par prix
      </a>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <li class="dropdown-item"><%= link_to "Croissant", cabans_path(order: "ASC"), class: "text-decoration-none" %></li>
        <li class="dropdown-item"><%= link_to "Décroissant", cabans_path(order: "DESC"), class: "text-decoration-none"%></li>
      </ul>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-6 grid-2-col" style="height: fit-content">
      <% @cabans.each do |caban| %>
        <%= link_to caban_path(caban), class:"text-decoration-none", style:"color: black; height: fit-content" do %>
          <div class="card-trip">


            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner" >
                <% caban.photos.each_with_index do |photo, index|%>

                  <% if index == 0 %>
                    <div class="carousel-item active">
                      <%= cl_image_tag photo.key, style:"width: 100%; height: 250px;", crop: :fill%>
                    </div>
                  <% else %>
                    <div class="carousel-item">
                      <%= cl_image_tag photo.key, style:"width: 100%; height: 250px;", crop: :fill%>
                    </div>
                  <% end %>

                <% end %>

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>

              </div>
            </div>

            <div class="card-trip-infos">
              <div>
                <h2><%=caban.name.capitalize %></h2>
                <p><i class="fa-solid fa-location-dot"></i> <%= caban.address.capitalize %></p>
              </div>
              <h2 class="card-trip-pricing"><%= caban.price %>€</h2>
            </div>

          </div>
        <% end %>

      <% end %>


    </div>


    <div class="col-6">
      <div style="height: 100vh; position: sticky; top: 0;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>



</div>
</div>

app/views/cabans/new.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1516528387618-afa90b13e000?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80); background-size: cover; min-height: calc(100vh - 150px); background-repeat: no-repeat">
  <div class="container p-5">
    <div class= "d-flex justify-content-center">
      <div class="form p-5" style="background:white; width: 500px">
        <h2 class="title">Nouvelle Cabane</h2>
        <%= simple_form_for [@caban] do |f| %>
          <%= f.input :name, placeholder: "Tarzan", label: "Nom" %>
          <p>Adresse</p>
          <%= f.input :address, as: :hidden, input_html: {data: {address_autocomplete_target: "address"}}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}, placeholder: "5 rue du Platane", class: "d-none"%>
          <%= f.input :price, placeholder: "100 €", label: "Prix par nuit" %>
          <%= f.input :description, placeholder: "La cabane est dans un arbre magnifique..." %>
          <%= f.input :photos, as: :file, input_html: { multiple: true }, class: "mr-auto p-2" %>
        <%= f.submit "Créer", class: "btn btn-primary p-2" %>
        <%= link_to "Retour", cabans_path, class: "btn p-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cabans/show.html.erb
<div class="container mt-3" style="width: 1200px;">
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner" style="height: 500px; border-radius: 3%;">
      <% @caban.photos.each_with_index do |photo, index| %>
      <% if index == 0 %>
        <div class="carousel-item active">
      <% else %>
        <div class="carousel-item">
      <% end %>
          <%= cl_image_tag photo.key, height: 500, width: 1200, crop: :fill %>
        </div>
      <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>



<div class="container mt-3" style="width: 1200px">
  <div class="container">
    <div class="card-trip-infos d-flex title border-bottom border-dark justify-content-between">
      <h2 class="card-title"><%= @caban.name.capitalize %></h2>
      <h3 class="card-text"><%= @caban.price %>€</h3>
    </div>
    <div class="infos mt-3">
      <h5 class="fst-italic">Découvrez cette magnifique cabane située : <%= @caban.address %></h5>
      <h5 class="card-text"><%= @caban.description.capitalize %></h5>
      <% if @caban.user != current_user %>
        <div class="d-flex align-items-center">
          <h5 class="card-text mb-0 me-2"> Votre super hôte :</h5>
          <% if @caban.user.photo.attached?%>
            <%= cl_image_tag @caban.user.photo.key, crop: :fit, class: "avatar me-2"%>
          <% else %>
            <%= image_tag "https://cdn.dribbble.com/userupload/2582751/file/original-f6ac5f1e412b80da59bcf4eaff521100.jpg?resize=400x0", class: "avatar me-2" %>
          <% end %>
          <h5 class="card-text"><%=@caban.user.first_name %></h5>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container d-flex justify-content-end">
    <% if @caban.user != current_user %>
      <div class="m-3">
        <%= link_to "Réserver", new_caban_booking_path(@caban), class: "btn btn-primary" %>
      </div>
    <% end %>
    <div class="m-3">
      <%= link_to "Retour", cabans_path(@cabans), class: "btn btn-primary" %>

    </div>
  </div>
  <div class="row mt-5 border-top align-items-center">

    <div class="col-6 mt-3">
        <p class="fs-3"><i class="fa-solid fa-location-dot"></i> Localisation</p>
        <div class="mt-3 mb-5" style="height: 500px;"
          data-controller="map"
          data-map-markers-value="<%= @marker.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </div>

    <div class="col-6 mt-3">
      <p class="fs-3"><i class="fa-solid fa-address-book"></i> Votre super hôte</p>
      <p class="fs-6">Adresse : <strong><%= @caban.address %></strong></p>
      <p class="fs-6">Contact : <strong><%= @caban.user.email %></strong></p>
      <p class="fs-6"> Votre logement proposé par : <strong><%= @caban.user.first_name.capitalize %> <%= @caban.user.last_name.capitalize %></strong>
          <% if @caban.user.photo.attached?%>
            <%= cl_image_tag @caban.user.photo.key, crop: :fit, class: "avatar me-2"%>
          <% else %>
            <%= image_tag "https://cdn.dribbble.com/userupload/2582751/file/original-f6ac5f1e412b80da59bcf4eaff521100.jpg?resize=400x0", class: "avatar me-2" %>
          <% end %>
      </p>
      <p class="fs-4"><i class="fa-solid fa-circle-info"></i> Ce que propose ce logement</p>
      <p class="fs-6"><i class="fa-solid fa-temperature-three-quarters"></i> Chauffage d'appoint</p>
      <p class="fs-6"><i class="fa-solid fa-tree"></i> Espace repas en plein air</p>
      <p class="fs-6"><i class="fa-solid fa-car"></i> Parking gratuit sur place</p>
      <p class="fs-6"><i class="fa-solid fa-kitchen-set"></i> Cuisine</p>
    </div>

  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="page" style="background: #EDF1D6; display: flex; flex-direction: column; min-height: calc(100vh - 150px);">
<div class="px-4 py-5 my-0 text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1516528387618-afa90b13e000?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80)">
  <h1 class="display-5 fw-bold" style="color: white"><i class="fa-sharp fa-solid fa-house-user"></i> Bienvenue dans votre dashboard <%= current_user.first_name %> ! </h1>
  <div class="col-lg-6 mx-auto">
      <p class="lead mb-4" style="color: #EDF1D6">Gérez vos cabanes, vos réservations et les réservations de vos clients</p>
  </div>
</div>

  <div class="row justify-content-center p-2" style="background: #EDF1D6;">


      <h3 class="text-center mt-2">Espace Locataire</h3>
    <div class="col-8 m-2 p-3" style="background: #EDF1D6; border-radius: 5px; box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
      <h6 class="text-start pb-3" style="color : #40513B"><strong>Mes demandes de réservation (<%= @bookings_as_r.count %>)</strong></h6>
      <% @bookings_as_r.each do |booking| %>
        <div class="card-product m-2" style="border-radius: 5px;  background: #EDF1D6">
          <%= link_to caban_path(booking.caban) do %>
            <% if booking.caban.photos.attached?%>
              <%= cl_image_tag booking.caban.photos.first.key %>
            <% end %>
          <% end %>
            <div class="card-product-infos" style="height: fit-content">
              <h2><%= booking.caban.name%></h2>
              <p><i class="fa-sharp fa-solid fa-calendar-days"></i> Du <%= booking.start_date.strftime('%d/%m/%Y') %> au <%= booking.end_date.strftime('%d/%m/%Y') %></p>
              <p> Total de la réservation : <strong><%= ((booking.end_date - booking.start_date).to_i) * booking.caban.price %> €</strong></p>
              <% if booking.status == "declined" %>
                <p class="btn btn-danger"><%= booking.status %></p>
              <% elsif booking.status == "accepted" %>
                <p class="btn btn-success"><%= booking.status %></p>
              <% else %>
                <p class="btn btn-warning"><%= booking.status %></p>
              <% end %>
            </div>
        </div>
        <% end %>
    </div>
      <h3 class="text-center mt-2">Espace Propriétaire</h3>
    <div class="col-4 m-2 p-3" style="background: #EDF1D6; border-radius: 5px; box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">

      <div class="d-flex justify-content-between">
        <div class="title">
          <h6 class="text-start" style="color : #40513B"><strong> Mes demandes de réservation (<%= @bookings_as_p.count %>)</strong></h6>
        </div>
        <div class="dropdown mb-1">
          <button class="btn btn-secondary btn-sm dropdown-toggle" style="background: #40513B; color: #EDF1D6" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" data-action="dropdown#toggle click@window->dropdown#hide" aria-expanded="false"><i class="fa-solid fa-filter"></i>
            Statuts
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu2" data-dropdown-target="menu"
            class="hidden transition transform origin-top-right absolute right-0"
            data-transition-enter-from="opacity-0 scale-95"
            data-transition-enter-to="opacity-100 scale-100"
            data-transition-leave-from="opacity-100 scale-100"
            data-transition-leave-to="opacity-0 scale-95">

            <li><%= link_to "Toutes", dashboard_path, class: "dropdown-item text-decoration-none text-dark" %></li>
            <li><%= link_to "Pending", dashboard_path(status: "pending"), class: "dropdown-item text-decoration-none text-dark" %></li>
            <li><%= link_to "Accepted", dashboard_path(status: "accepted"), class: "dropdown-item text-decoration-none text-dark" %></li>
            <li><%= link_to "Refused", dashboard_path(status: "declined"), class: "dropdown-item text-decoration-none text-dark" %></li>
          </ul>
        </div>
      </div>

      <% @bookings_as_p.each do |booking| %>
      <div class="card-product m-2" style="border-radius: 5px; background: #EDF1D6">
        <% if booking.caban.photos.attached?%>
          <%= cl_image_tag booking.caban.photos.first.key %>
        <% end %>
        <div class="card-product-infos" style="height: fit-content">
          <h2 ><%= booking.caban.name%></h2>
            <p><i class="fa-sharp fa-solid fa-calendar-days"></i> Du <%= booking.start_date.strftime('%d/%m/%Y') %> au <%= booking.end_date.strftime('%d/%m/%Y') %></p>
            <p> Total de la réservation : <strong><%= ((booking.end_date - booking.start_date).to_i) * booking.caban.price %> €</strong></p>
            <% if booking.status == "declined" %>
              <p class="btn btn-danger"><%= booking.status %></p>
            <% elsif booking.status == "accepted" %>
              <p class="btn btn-success"><%= booking.status %></p>
            <% else %>
              <p class="btn btn-warning"><%= booking.status %></p>
            <% end %>
        </div>
          <div class="d-flex flex-column pt-2 pb-2">
            <%= link_to accept_booking_path(booking), class: "text-decoration-none text-success" do %>
              <i class="fa-sharp fa-solid fa-square-check text-success"></i>
            <% end %>
            <%= link_to refuse_booking_path(booking), class: "text-decoration-none text-danger" do %>
              <i class="fa-solid fa-ban text-danger"></i>
            <% end %>
          </div>
      </div>
      <% end %>
    </div>

    <div class="col-4 m-2 p-3" style="background: #EDF1D6; border-radius: 5px; box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
        <h6 class="text-start pb-3" style="color : #40513B"><strong>Liste de mes cabanes</strong></h6>

          <% @cabans_as_p.each do |caban| %>
              <div class="card-product m-2" style="border-radius: 5px; background: #EDF1D6;">
                <% if caban.photos.attached?%>
                  <%= cl_image_tag caban.photos.first.key %>
                <% end %>
                <div class="card-product-infos" style="height: fit-content">
                    <h2><%=caban.name %></h2>
                    <p><%= caban.price %>€</p>
                    <p class="fw-normal fst-italic"><i class="fa-solid fa-location-dot"></i> <%= caban.address %></p>
                </div>
                <div class="d-flex flex-column">
                  <%= link_to caban_path(caban), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"text-decoration-none text-dark" do %>
                    <i class="fa-solid fa-trash-can m-2 text-dark"></i>

                  <% end %>
                  <%= link_to edit_caban_path(caban), class:"text-decoration-none text-dark" do %>
                    <i class="fa-solid fa-pen-to-square m-2 text-dark"></i>

                  <% end %>
                </div>
              </div>
          <% end %>
          <div class="d-flex justify-content-end">
            <%= link_to new_caban_path do %>
              <i class="fa-solid fa-plus"></i>
              Ajouter une cabane
            <% end %>
          </div>
    </div>

  </div>

  <div>

  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1582880421648-a7154a8c99c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80); min-height: calc(100vh - 150px);">
  <div class="container" style="width: 900px">
    <h1 class="fs-1 pb-3" style="color:#EDF1D6"><strong>Dormez dans les arbres : Découvrez nos cabanes suspendues uniques en leur genre</strong></h1>
    <p style="color:#EDF1D6"><span data-controller="typed-js"></span></p>
    <div class="d-flex justify-content-center">
      <div class="m-3">
        <%= link_to "Réserver une cabane", cabans_path, class: 'btn btn-flat pb-3 pt-3', style:"color:#EDF1D6" %>
      </div>
      <div class="m-3">
        <%= link_to "Ajouter ma cabane", new_caban_path, class: 'btn btn-flat pb-3 pt-3', style:"color:#EDF1D6" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
  <div class="d-flex justify-content-center">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "TARZ_N_B-removebg-preview.png", class: "navbar-logo" %>
    <% end %>
  </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Toutes les cabanes", cabans_path, class: "nav-link", id: "nav-link-right" %>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.photo.attached?%>
              <%= cl_image_tag current_user.photo.key, crop: :fit, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "TARZ_N_B-removebg-preview.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown"}, 'aria-haspopup': true, 'aria-expanded': false  %>
            <% end %>

            <span style="color:#EDF1D6"><%= current_user.first_name.capitalize %></span>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>